import React, { useContext } from 'react'
import Head from 'next/head'
/* import type {
  NextPage,
  GetServerSideProps,
  GetServerSidePropsContext,
  NextComponentType,
  NextPageContext,
} from 'next' */
// import { useRouter } from 'next/router'
// import Link from 'next/link'
// import type { AppProps, AppContext } from 'next/app'
// import { useRouter } from 'next/router'
// import axios from 'axios'

import { AuthGlobalHeader } from '@/components/_global/AuthGlobalHeader'
import { GlobalHeader } from '@/components/_global/GlobalHeader'

// global context
import { AuthAppContext } from '@/components/container/AuthAppProviderContainer'

import { routes } from '@/AppRouterConfig'

type Props = {
  children?: JSX.Element
}

export type GlobalNavigationGuardHandlerType = {
  navigationGuardHandler: () => Promise<void>
}

/* export async function getServerSideProps() {
  //  const res = await fetch(`https://google.com`)
  const res = await axios.get(`https://google.com`)
  const posts = await res.headers
  // console.log(posts)
  console.log('layout component: ' + JSON.stringify(posts, null, 2))

  // TODO やはりgetServerSideProps()内ではuseRouterは使えない。
  // const router = useRouter()
  // router.push('/login')
  return { props: { posts } }
} */

/* export async function getServerSideProps() {
  const res = await fetch(`https://gogle.com`);
  const posts = await res.json();
  console.log(posts);
  return { props: { posts } };
} */

export const Layout: React.VFC<Props> = ({ children = undefined }) => {
  const { getAuthId } = useContext(AuthAppContext)

  // return <>{children}</>
  return (
    <>
      <Head>
        <title>Sample Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/admin/favicon.ico" />
      </Head>

      {getAuthId() !== null ? (
        <AuthGlobalHeader
          routes={routes.filter(
            (route) => !(route.path === '/login' || route.path === '*')
          )}
        />
      ) : (
        <GlobalHeader />
      )}
      {children}
    </>
  )
}

export default Layout
