CREATE DATABASE IF NOT EXISTS nihil CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON nihil.* TO 'root'@'%';

FLUSH PRIVILEGES;
